### ISSUE TITLE
my-workout branch issues

### ISSUE THREAD

**Issue by rafi-d-z** [rafi-d-z/MusclMate#18]
There is a filelock issue, Vercel gives me a "Command "pnpm run build" exited with 1" error. (Fahad's issue)

Create another file in src called workout.tsx and move your work in there. Then in main.tsx, import your function from workout.tsx with the webpage and replace <MainMenu/> with the imported function. **PLEASE ASK FOR HELP IF YOU NEED IT THERE IS NO POINT IN WASTING TIME TRYING TO FIGURE IT OUT BY YOURSELF IF YOURE STRUGGLING.** (Chengsui's issue)

**Comment by LordFarquaadtheCreator** [comment]
i think this is resolved?
