### ISSUE TITLE
review jkim3273-main

### ISSUE THREAD

**Issue by rafi-d-z** [rafi-d-z/MusclMate#22]
Review this branch to see if we still need it. Pretty sure this was the branch with the initial homepage which i merged a while back.

**Comment by jkim3273** [comment]
Nah we don't need it although weren't you saying it would be better to use branches instead of forks to work on the project?

**Comment by rafi-d-z** [comment]
yea but we dont need branches that dont do much. also instead of having a personal branch, make a branch and dedicate it to a specific feature or deliverable

**Comment by jkim3273** [comment]
Alright, you can delete it then.

**Comment by jkim3273** [comment]
I'm guessing you're doing this to keep track of everything that's being done if I'm correct.
